# Travis Ci

language: node_js
node_js:
  - "0.12"

before_install:
  - npm install -g strongloop grunt-cli cordova ionic

before_script:
  - mkdir /tmp/build                  # Packaged apps will go there

script: .travis/script.sh

build:
  - currentfolder=${CI_HOME/api/}     # Build api package
  - slc build --pack

  #- currentfolder=${CI_HOME/api/}     # Build ionic android package
  #- ionic platform add android
  #- ionic build --release android

notifications:
  email:
    - $BUILD_NOTIFICATION_EMAIL
